import type { Metadata } from 'next'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import './globals.css'
import zealLogo from '../public/zeal-automotive-logo.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function Header(): JSX.Element {
  return (
    <header className="flex flex-row fixed left-0 top-0 items-center w-full bg-white p-3">
      <Image
        src={zealLogo}
        alt="Zeal Automotive Logo"
        // className="dark:invert"
        width={200}
        height={24}
        priority
      />
      <nav className="flex flex-row w-full justify-end">
        <ul className="flex flex-row content-center">
          <li className="m-2 text-black">MenuOption1</li>
          <li className="m-2 text-black">MenuOption2</li>
          <li className="m-2 text-black">MenuOption3</li>
          <li className="m-2 text-black">MenuOption4</li>
          <li className="m-2 text-black">MenuOption5</li>
          <li className="m-2 text-black">MenuOption6</li>
        </ul>
      </nav>
    </header>
  )
}

export function Footer(): JSX.Element {
  return (
    <footer className="w-full h-16 text-black flex justify-center items-center">
      footer content
    </footer>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
